version: '3.8'

services:
  init:
    image: grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo-data:/var/tempo
      
  loki:
    image: grafana/loki:latest
    ports:
      - "3100"
    command: [ "-config.file=/etc/loki.yaml" ]
    volumes:
      - ./loki.yaml:/etc/loki.yaml
    depends_on:
      - init

  tempo:
    image: grafana/tempo:latest
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "9095" # tempo grpc
      - "4317"  # otlp grpc
      - "4318"  # otlp http
      - "9411"   # zipkin
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
    depends_on:
      - init

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-collector-config.yml:/etc/otel/config.yml
    command: --config /etc/otel/config.yml
    ports:
      - "4317"
      - "55681"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    depends_on:
      # - loki
      - tempo

  agave-app:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - SERVICENAME=agave-silo
      - USELOGEXPORTER=otlp
      - USETRACINGEXPORTER=otlp
      - OPENTELEMETRY_INCLUDEFORMATTEDMESSAGE=true
      - OPENTELEMETRY_INCLUDESCOPES=true
      - OPENTELEMETRY_PARSESTATEVALUES=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    depends_on:
      - otel-collector
      - loki
      - tempo
