receivers:
  otlp:
    protocols:
      grpc:
        include_metadata: true
      http:
        include_metadata: true
processors:
  attributes:
    actions:
      - key: loki.attribute.labels
        action: insert
        value: deployment.environment, telemetry.sdk.language, grainId, service.version
  transform/drop_unneeded_resource_attributes:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - delete_key(attributes, "{OriginalFormat}")
exporters:
  otlp/trace:
    endpoint: http://tempo:4317
    tls:
      insecure: true
      insecure_skip_verify: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    default_labels_enabled:
      exporter: false
    tls:
      insecure: true
      insecure_skip_verify: true
  debug:
    verbosity: detailed
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/trace, debug]
    logs:
      receivers: [otlp]
      processors: [attributes, transform/drop_unneeded_resource_attributes]
      exporters: [loki]